#!/bin/bash
# gitignore-manager.sh
# .gitignore 패턴 관리 유틸리티
#
# 사용법:
#   source .claude/lib/gitignore-manager.sh
#
#   # 단일 패턴 추가
#   add_to_gitignore "*.log"
#
#   # 설치 패턴 일괄 추가
#   add_installer_patterns_to_gitignore
#
# 의존성:
#   - grep (기본 도구)

set -e

# ════════════════════════════════════════════════════════════════════════════
# 표준 설치 패턴 정의
# ════════════════════════════════════════════════════════════════════════════

# Claude Workflows Installer가 자동으로 추가하는 .gitignore 패턴
readonly INSTALLER_GITIGNORE_PATTERNS=(
    # Claude Workflows 디렉토리 전체
    ".claude/"

    # Specify 디렉토리 전체
    ".specify/"

    # Log files
    "*.log"

    # Temporary files
    "*.tmp"

    # OS-specific files
    ".DS_Store"
    "Thumbs.db"

    # IDE files
    ".idea/"
    ".vscode/"
    "*.swp"
    "*.swo"
    "*~"
)

# ════════════════════════════════════════════════════════════════════════════
# .gitignore 패턴 추가 (중복 방지)
# ════════════════════════════════════════════════════════════════════════════

# .gitignore 파일에 패턴을 추가합니다 (이미 존재하면 건너뜀).
#
# @param $1 pattern (.gitignore에 추가할 패턴)
# @param $2 gitignore_file (선택, 기본값: .gitignore)
# @return 0 성공 (추가 또는 이미 존재), 1 실패
#
# @example
#   add_to_gitignore "*.log"
#   add_to_gitignore "node_modules/" ".gitignore"
add_to_gitignore() {
    local pattern="$1"
    local gitignore_file="${2:-.gitignore}"

    # 패턴 필수
    if [[ -z "$pattern" ]]; then
        echo "오류: 패턴이 필요합니다" >&2
        return 1
    fi

    # .gitignore 파일 생성 (없으면)
    if [[ ! -f "$gitignore_file" ]]; then
        touch "$gitignore_file"
        echo "# Auto-generated by Claude Workflows Installer" > "$gitignore_file"
        echo "ℹ️  .gitignore 파일 생성됨: $gitignore_file"
    fi

    # 중복 확인 (정확한 일치, 고정 문자열 검색)
    if grep -Fxq "$pattern" "$gitignore_file" 2>/dev/null; then
        # 이미 존재하면 무시
        return 0
    fi

    # 패턴 추가
    echo "$pattern" >> "$gitignore_file"
    echo "  + $pattern"
    return 0
}

# ════════════════════════════════════════════════════════════════════════════
# 설치 패턴 일괄 추가
# ════════════════════════════════════════════════════════════════════════════

# Claude Workflows Installer의 표준 패턴을 .gitignore에 추가합니다.
#
# @param $1 gitignore_file (선택, 기본값: .gitignore)
# @return 0 성공, 1 실패
#
# @example
#   add_installer_patterns_to_gitignore
#   add_installer_patterns_to_gitignore "/path/to/.gitignore"
add_installer_patterns_to_gitignore() {
    local gitignore_file="${1:-.gitignore}"

    echo "ℹ️  .gitignore 업데이트 중..."

    # 섹션 헤더 추가 (처음에만)
    # Check for either "# Auto-generated by Claude Workflows Installer" or "# Claude Workflows Installer"
    if [[ -f "$gitignore_file" ]] && ! grep -qE "# (Auto-generated by )?Claude Workflows Installer" "$gitignore_file"; then
        echo "" >> "$gitignore_file"
        echo "# ════════════════════════════════════════════════════════════════" >> "$gitignore_file"
        echo "# Claude Workflows Installer - Auto-generated" >> "$gitignore_file"
        echo "# ════════════════════════════════════════════════════════════════" >> "$gitignore_file"
        echo ""
    fi

    # 각 패턴 추가
    local added_count=0
    for pattern in "${INSTALLER_GITIGNORE_PATTERNS[@]}"; do
        if add_to_gitignore "$pattern" "$gitignore_file"; then
            ((added_count++)) || true
        fi
    done

    echo ""
    echo "✓ .gitignore 업데이트 완료 (${added_count}개 패턴 처리)"
    return 0
}

# ════════════════════════════════════════════════════════════════════════════
# Git 상태 확인
# ════════════════════════════════════════════════════════════════════════════

# .gitignore 업데이트 후 Git 상태를 확인합니다.
#
# @return 0 깨끗한 상태 (추적되지 않은 파일 없음), 1 추적되지 않은 파일 있음
#
# @example
#   verify_git_status && echo "Git 상태 깨끗함" || echo "추적되지 않은 파일 있음"
verify_git_status() {
    if ! command -v git &> /dev/null; then
        echo "⚠️  Git이 설치되지 않아 상태 확인을 건너뜁니다."
        return 0
    fi

    # Git 저장소 확인
    if ! git rev-parse --git-dir &> /dev/null; then
        echo "⚠️  Git 저장소가 아니므로 상태 확인을 건너뜁니다."
        return 0
    fi

    echo ""
    echo "ℹ️  Git 상태 확인 중..."

    # 추적되지 않은 파일 확인
    local untracked
    untracked=$(git ls-files --others --exclude-standard | wc -l | tr -d ' ')

    if [[ "$untracked" -eq 0 ]]; then
        echo "✓ Git 상태 깨끗함 (추적되지 않은 파일: 0개)"
        return 0
    else
        echo "⚠️  추적되지 않은 파일: ${untracked}개"
        echo "   다음 명령어로 확인하세요: git status"
        return 1
    fi
}

# ════════════════════════════════════════════════════════════════════════════
# END OF FILE
# ════════════════════════════════════════════════════════════════════════════
